import type { ExplorablePlanet, MissionChartData, Mission } from "@/types/types";

export const PLANETS: ExplorablePlanet[] = [
  {
    id: "mercury",
    name: "Merkury",
    type: "rocky",
    description:
      "Najmniejsza i najbliższa Słońcu planeta Układu Słonecznego. Posiada ekstremalnie cienką atmosferę.",
    distanceFromSun: 57.9,
    diameter: 4879,
    gravity: 0.38,
    temperature: 167,
    image: "/planets/mercury.svg",
    color: "#b5b5b5",
    missionsCount: 3,
    lastExplored: "2025-04",
    explorationStatus: "completed",
    dangerLevel: 7,
  },
  {
    id: "venus",
    name: "Wenus",
    type: "rocky",
    description:
      "Druga planeta od Słońca, znana jako 'bliźniacza siostra Ziemi'. Ekstremalnie gorąca atmosfera.",
    distanceFromSun: 108.2,
    diameter: 12104,
    gravity: 0.91,
    temperature: 464,
    image: "/planets/venus.svg",
    color: "#e8cda0",
    missionsCount: 5,
    lastExplored: "2025-08",
    explorationStatus: "in-progress",
    dangerLevel: 9,
  },
  {
    id: "mars",
    name: "Mars",
    type: "rocky",
    description:
      "Czerwona Planeta — główny cel kolonizacji. Posiada cienką atmosferę i ślady wody.",
    distanceFromSun: 227.9,
    diameter: 6779,
    gravity: 0.38,
    temperature: -65,
    image: "/planets/mars.svg",
    color: "#c1440e",
    missionsCount: 12,
    lastExplored: "2026-01",
    explorationStatus: "in-progress",
    dangerLevel: 4,
  },
  {
    id: "jupiter",
    name: "Jowisz",
    type: "gas-giant",
    description:
      "Największa planeta Układu Słonecznego. Posiada Wielką Czerwoną Plamę — burzę trwającą od wieków.",
    distanceFromSun: 778.5,
    diameter: 139822,
    gravity: 2.53,
    temperature: -110,
    image: "/planets/jupiter.svg",
    color: "#c88b3a",
    missionsCount: 8,
    lastExplored: "2025-11",
    explorationStatus: "planned",
    dangerLevel: 8,
  },
  {
    id: "saturn",
    name: "Saturn",
    type: "gas-giant",
    description:
      "Znany ze swoich spektakularnych pierścieni. Drugi co do wielkości gazowy olbrzym.",
    distanceFromSun: 1434,
    diameter: 116460,
    gravity: 1.07,
    temperature: -140,
    image: "/planets/saturn.svg",
    color: "#ead6a6",
    missionsCount: 4,
    lastExplored: "2024-06",
    explorationStatus: "completed",
    dangerLevel: 6,
  },
  {
    id: "neptune",
    name: "Neptun",
    type: "ice-giant",
    description:
      "Najdalsza planeta od Słońca. Lodowy olbrzym z najsilniejszymi wiatrami w Układzie Słonecznym.",
    distanceFromSun: 4495,
    diameter: 49528,
    gravity: 1.14,
    temperature: -200,
    image: "/planets/neptune.svg",
    color: "#5b5ddf",
    missionsCount: 1,
    lastExplored: "2023-12",
    explorationStatus: "planned",
    dangerLevel: 5,
  },
];

export const MISSION_CHART_DATA: MissionChartData[] = [
  { month: "Sty", missions: 3, discoveries: 1 },
  { month: "Lut", missions: 5, discoveries: 2 },
  { month: "Mar", missions: 4, discoveries: 3 },
  { month: "Kwi", missions: 7, discoveries: 4 },
  { month: "Maj", missions: 6, discoveries: 2 },
  { month: "Cze", missions: 9, discoveries: 5 },
  { month: "Lip", missions: 8, discoveries: 6 },
  { month: "Sie", missions: 11, discoveries: 7 },
  { month: "Wrz", missions: 10, discoveries: 5 },
  { month: "Paź", missions: 13, discoveries: 8 },
  { month: "Lis", missions: 12, discoveries: 9 },
  { month: "Gru", missions: 15, discoveries: 11 },
];

export const RECENT_MISSIONS: Mission[] = [
  {
    id: "m1",
    name: "Ares Pathfinder",
    destination: "Mars",
    status: "in-progress",
    crewSize: 6,
    startDate: "2025-09-15",
    endDate: null,
  },
  {
    id: "m2",
    name: "Venus Surveyor",
    destination: "Wenus",
    status: "completed",
    crewSize: 4,
    startDate: "2025-03-01",
    endDate: "2025-08-22",
  },
  {
    id: "m3",
    name: "Jupiter Deep Probe",
    destination: "Jowisz",
    status: "planned",
    crewSize: 8,
    startDate: "2026-06-01",
    endDate: null,
  },
  {
    id: "m4",
    name: "Saturn Ring Mapper",
    destination: "Saturn",
    status: "completed",
    crewSize: 5,
    startDate: "2024-01-10",
    endDate: "2024-06-15",
  },
  {
    id: "m5",
    name: "Neptune Ice Explorer",
    destination: "Neptun",
    status: "planned",
    crewSize: 7,
    startDate: "2027-01-01",
    endDate: null,
  },
];
